"""змiна таблицi  операцiй

Revision ID: 046a528490ff
Revises: 
Create Date: 2023-07-12 13:35:58.111137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046a528490ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_denzvits_id'), 'denzvits', ['id'], unique=False)
    op.create_index(op.f('ix_marshryts_id'), 'marshryts', ['id'], unique=False)
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_index(op.f('ix_nakladnas_id'), 'nakladnas', ['id'], unique=False)
    op.create_index(op.f('ix_odvumirs_id'), 'odvumirs', ['id'], unique=False)
    op.create_index(op.f('ix_operations_id'), 'operations', ['id'], unique=False)
    op.create_index(op.f('ix_opers_id'), 'opers', ['id'], unique=False)
    op.create_index(op.f('ix_pereliks_id'), 'pereliks', ['id'], unique=False)
    op.create_index(op.f('ix_prices_id'), 'prices', ['id'], unique=False)
    op.create_index(op.f('ix_resurs_id'), 'resurs', ['id'], unique=False)
    op.create_index(op.f('ix_robitnuks_id'), 'robitnuks', ['id'], unique=False)
    op.create_index(op.f('ix_units_id'), 'units', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_units_id'), table_name='units')
    op.drop_index(op.f('ix_robitnuks_id'), table_name='robitnuks')
    op.drop_index(op.f('ix_resurs_id'), table_name='resurs')
    op.drop_index(op.f('ix_prices_id'), table_name='prices')
    op.drop_index(op.f('ix_pereliks_id'), table_name='pereliks')
    op.drop_index(op.f('ix_opers_id'), table_name='opers')
    op.drop_index(op.f('ix_operations_id'), table_name='operations')
    op.drop_index(op.f('ix_odvumirs_id'), table_name='odvumirs')
    op.drop_index(op.f('ix_nakladnas_id'), table_name='nakladnas')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.drop_index(op.f('ix_marshryts_id'), table_name='marshryts')
    op.drop_index(op.f('ix_denzvits_id'), table_name='denzvits')
    # ### end Alembic commands ###
