"""Update table structures

Revision ID: 7a62a9d8171e
Revises: 
Create Date: 2023-05-10 15:24:56.812161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a62a9d8171e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   None
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    None
    # ### end Alembic commands ###
