"""Update table structures

Revision ID: 7a62a9d8171e
Revises: 
Create Date: 2023-05-10 15:24:56.812161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a62a9d8171e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'marka')
    op.drop_column('materials', 'profile')
    op.add_column('materials', sa.Column('id_perelik', sa.Integer(), nullable=True))
    op.add_column('materials', sa.Column('id_odvumir', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'materials', 'pereliks', ['id_perelik'], ['id'])
    op.create_foreign_key(None, 'materials', 'odvumirs', ['id_odvumir'], ['id'])  
    op.add_column('resurs', sa.Column('number', sa.Integer(), nullable=True))
    op.drop_column('resurs', 'inumber')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resurs', sa.Column('inumber', sa.INTEGER(), nullable=True))
    op.drop_column('resurs', 'number')
    op.add_column('materials', sa.Column('profile', sa.VARCHAR(), nullable=True))
    op.add_column('materials', sa.Column('marka', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_column('materials', 'id_odvumir')
    op.drop_column('materials', 'id_perelik')
    # ### end Alembic commands ###
