"""users password

Revision ID: 94ca7c80f59e
Revises: 5338524d8d3c
Create Date: 2023-07-09 18:28:38.855344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ca7c80f59e'
down_revision = '5338524d8d3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    op.drop_column('users', 'pasword')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pasword', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
